### PR TITLE
Update and include the project's code of conduct

### PR DESCRIPTION
**Pull request by calleerlandsson**
@mptre and @mike-burns, what do you think about the updated code of conduct?

Would you like to receive email for the <pick-maintainers@calleerlandsson.com> alias?

### CODE REVIEW

**Comment by mptre** [comment]
Sorry, I know to little to comment on the matter.

**Comment by mike-burns** [comment]
LGTM, and yes I will gladly be on the contact list of the code of conduct.

**Comment by calleerlandsson** [comment]
Thanks for the feedback!

@mptre would you be OK abiding by the suggested code of conduct and being on the contact list for it?

**Comment by mptre** [comment]
> @mptre would you be OK abiding by the suggested code of conduct and
> being on the contact list for it?

Of course!

**Comment by calleerlandsson** [comment]
Great! I'll merge this.

**Pull request merged**
