### PR TITLE
Exit on empty set of choices

### PR DESCRIPTION
**Pull request by DBOTW**
```sh
echo -n "" | pick
```
should not come up with a selection ...

### CODE REVIEW

**Comment by DBOTW** [comment]
> See #62.

OK, I've not digged in the cementary of issues ... but see no decision in #62  ... close this also?

**Comment by mptre** [comment]
See #62.

**Comment by mptre** [comment]
I'm not in favor of the proposed behavior. Other interactive utilities
such as less/more does not exit in the case of absent input:

```sh
$ less </dev/null
```

**Comment by DBOTW** [comment]
> Other interactive utilities such as less/more does not exit in the case of absent input

Can't confirm this for: `cat` and `more` on HP-UX 10.20, NetBSD 7.1 & Solaris 9, `cat` from GNU coreutils 8.23, `more` from  util-linux 2.25.2, `less` (358, 458 and 481) ...

**Pull request closed without merging**
