### PR TITLE
Optimize redrawing of choices

### PR DESCRIPTION
**Pull request by DBOTW**
... each time the cursor moves only in the input query field all choices are printed again even though nothing has changed ... this PR avoids the unnecessary redraw and saves some CPU cycles ... ;-)

### CODE REVIEW

**Comment by mptre** [comment]
Thanks. I agree in principle that this is more efficient but wonder if
it improves the responsiveness of the UI? Do you experience
flickering/rendering artefacts without this diff applied?

**Comment by DBOTW** [comment]
Using `pick` over a serial terminal line (VT520 with 38400 baud rate) it improves cursor movement drastically ... believe me: you don't want a full screen redraw each time on such terminals ... ;-)

**Comment by mptre** [comment]
Sorry for taking so long. See #264 for a slightly different approach,
reducing the necessary indent level a bit.

**Comment by DBOTW** [comment]
Thanks, I'm closing this in favor of #264 ...

**Comment by mptre** [comment]
Great, I'm planning on doing a release tomorrow.

**Pull request closed without merging**
