### PR TITLE
Some more Emacs key bindings

### PR DESCRIPTION
**Pull request by DBOTW**
Like "Ctrl-P/Ctrl-N" for "Up/Down" there should be some key bindings for other "special keys" as well.

### CODE REVIEW

**Comment by mptre** [comment]
Are those key bindings de facto standard for moving vertically
somewhere?

**Comment by DBOTW** [comment]
"less"uses them too ... may be useful on machines where "special keys" are not available; I think that was the reason for adding "Ctrl-P" and "Ctrl-N" ...

**Comment by calleerlandsson** [comment]
I'm happy to support key bindings used by common utilities and I think this looks good to merge! Thanks for working on this @DBOTW!

**Comment by mptre** [comment]
That went a bit too fast, I would like to see tests for the new keys.

**Comment by calleerlandsson** [comment]
Oh yeah, good point, @mptre. That way we won't break the key bindings going forward.

**Pull request merged**
