### PR TITLE
Allow special chars as word seperators

### PR DESCRIPTION
**Pull request by DBOTW**
... numbers are also "words" ...

### CODE REVIEW

**Comment by calleerlandsson** [comment]
Hey @DBOTW, thanks for the PR!

The implementation looks good to me.

I haven't been able to find a standard definition of the `ALTWERASE` mode. The GNU libc documentation mentions also counting underscores as word characters and it seems like the handling built into linux also does this: https://github.com/torvalds/linux/blob/2acf097f16abba684012cca670a61d94178bd1ab/drivers/tty/n_tty.c#L998

Do you know more about `ALTWERASE`, @mptre?

**Comment by DBOTW** [comment]
For me an underscore "combines" words (like a "visible blank"), I don't care about `ALTWERASE` ... ;-)

**Comment by mptre** [comment]
The OpenBSD kernel also treats underscore as a word character. I would
propose us doing something as follows:

```c
#define	ISWORD(c)	(isalnum((c)) || (c) == '_')
```

The macro is not necessary if the line with the conditional doesn't get
excessively long.

**Comment by mptre** [comment]
The manual must be updated as well:

```diff
diff --git pick.1 pick.1
index 0d5104e..efc1c84 100644
--- pick.1
+++ pick.1
@@ -74,8 +74,10 @@ Delete one character to the left of the cursor in the search query input field.
 .It Ic Delete | Ctrl-D
 Delete the character under the cursor in the search query input field.
 .It Ic Ctrl-W
-Delete to the beginning of the closest word to the left in the search query
-input field.
+Delete the word to the left of the cursor.
+A word is recognized as a sequence of characters for which either
+.Xr isalnum 3
+is true or the character is an underscore.
 .It Ic Ctrl-U
 Delete to the beginning of the line in the search query input field.
 .It Ic Ctrl-K
```

**Comment by mptre** [comment]
@DBOTW are you up for the task of finishing this PR with respect to the
feedback above? Otherwise, no worries; I will go ahead and fix it.

**Comment by DBOTW** [comment]
Of course @mptre ... done ...

**Comment by calleerlandsson** [comment]
Thanks, @DBOTW! This looks good to me.

**Comment by mptre** [comment]
This have to wait until v1.8.0 is out. I would also like to make
some final adjustment.

**Comment by mptre** [comment]
Closing in favor of #234.

**Pull request closed without merging**
