### PR TITLE
Alternative keys for Ctrl-W & Page-Down

### PR DESCRIPTION
**Pull request by DBOTW**
`less` uses `Alt-Space` for `Page-Down` and `Alt-Backspace` seems common for `Ctrl-W` ...

### CODE REVIEW

**Comment by mptre** [comment]
Loooks good. @calleerlandsson thoughts?

**Comment by calleerlandsson** [comment]
Looks good. I'm happy that supporting alternative key-bindings is so easy now!

**Comment by mptre** [comment]
> Looks good. I'm happy that supporting alternative key-bindings is so easy now!

Indeed!

Merged with some modifications as 7d0a568.

**Comment by DBOTW** [comment]
Cool! Thanks for merging!

**Pull request closed without merging**
