### PR TITLE
Recognize alphanumeric and underscore characters as words

### PR DESCRIPTION
**Pull request by mptre**
This is equivalent to the ALTWERASE algorithm.

Based on previous work done by Jenz Guenther in PR #231 but further
enhanced to support UTF-8.

### CODE REVIEW

**Comment by mptre** [comment]
Anyone? Both testing and code inspection would be much appreciated.

/cc @calleerlandsson @mike-burns @teoljungberg @DBOTW

**Comment by DBOTW** [comment]
Tested and works on `Debian (testing)` and `NetBSD 7.1` ...

**Comment by mptre** [comment]
Thanks, merged.

**Comment by calleerlandsson** [comment]
Thanks @mptre! Works well on macOS 10.12.6 too.

**Pull request merged**
