### PR TITLE
Add missing tests for Emacs keys

### PR DESCRIPTION
**Pull request by DBOTW**
Probably something is bound to Ctrl-V that make some of the tests fail ...

### CODE REVIEW

**Comment by calleerlandsson** [comment]
I think this is failing because Ctrl-V is mapped to the `lnext` special character in Terminal on macOS:

```
~/Projects/pick$ stty -a
speed 9600 baud; 44 rows; 80 columns;
lflags: icanon isig iexten echo echoe -echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
	-extproc
iflags: -istrip icrnl -inlcr -igncr ixon -ixoff ixany imaxbel iutf8
	-ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr -oxtabs -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
	min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
	stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

The `termios(4)` man page states:

```
LNEXT   Special character on input and is recognized if the IEXTEN flag
             is set.  Receipt of this character causes the next character to
             be taken literally.
```

Because of this, typing Ctrl-V Ctrl-V has the intended effect of Ctrl-V. As described by the man page, disabling `IEXTEN` seems to solve this:

```diff
diff --git a/pick.c b/pick.c
index ecbb46c..10e7bc7 100644
--- a/pick.c
+++ b/pick.c
@@ -642,7 +642,7 @@ tty_init(void)
        tcgetattr(fileno(tty_in), &original_attributes);
        new_attributes = original_attributes;
        new_attributes.c_iflag |= ICRNL;        /* map CR to NL */
-       new_attributes.c_lflag &= ~(ICANON | ECHO);
+       new_attributes.c_lflag &= ~(ICANON | ECHO | IEXTEN);
        tcsetattr(fileno(tty_in), TCSANOW, &new_attributes);
 
        if ((tty_out = fopen("/dev/tty", "w")) == NULL)
```

@DBOTW and @mptre, could you try applying the above and see if it still works on your machines?

**Comment by DBOTW** [comment]
% `echo $TERM`
rxvt-unicode
% `stty -a | grep lnext`
werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;

seems not to be the problem (only https://travis-ci.org/calleerlandsson/pick/jobs/250531001 fails) ...

**Comment by DBOTW** [comment]
Thanks, @calleerlandsson, that fixes it: `iexten` is already set here by default, so the checks passed.

**Comment by mptre** [comment]
Great work everyone, isn't nice that the test suite can spot bugs like
the one related to `IEXTEN`.

Committed with some modification: 99152e2 and 8a70fe7. Mainly making use
of the `LINES` environment variable, see 369eb66.

**Pull request closed without merging**
