### PR TITLE
Tag or untag selected choices

### PR DESCRIPTION
**Pull request by DBOTW**
... simple tagging-mechanism:
tagged

### CODE REVIEW

**Comment by calleerlandsson** [comment]
Hey @DBOTW, cool proposal! Thanks for the great GIF showing how it works!

I'm a bit hesitant towards merging this for the same reasons as #226. Could you tell us a bit more about your use-case?

What are your thoughts, @mptre?

**Comment by DBOTW** [comment]
Thanks @calleerlandsson, saw this is in other `fuzzy finders` and thought it would be "amusing" to move around and select stuff from the list ... I'm not really expecting this to be merged ... think of it as a "playground", although it can be useful for selecting filenames and pass them to an application/command or something like that ... I fully understand that `pick` should be simple and not overloaded with such "features", but I also wanted to post a GIF that looks cool ... ;-)

**Comment by mptre** [comment]
> What are your thoughts, @mptre?

Neat idea indeed but I haven't felt the need myself for such a feature.

**Comment by calleerlandsson** [comment]
I think this feature is cool and can definitely see how it could be useful but until we have a strong use-case, I'd rather hold off on merging this in favor of lower complexity.

I want to emphasize that I don't wish to discourage you from contributing to pick. I'm also happy to discuss this feature again in the future.

**Comment by DBOTW** [comment]
No worries, @calleerlandsson: I'm always happy to contribute to `pick` as a hobbyist with no professional background ... :-) I'm also very grateful, that @mptre looks critical over my PRs and points me to alternative (mostly obviously) ways to solve the problem ...

**Pull request closed without merging**
