### PR TITLE
Setup crucial environment for pick in pick-test

### PR DESCRIPTION
**Pull request by mptre**
Instead of doing [this][homebrew], `pick-test(1)` should setup the environment
needed by `pick(1)`.
Once the released the referenced line could be removed from the homebrew
recipe.

Thoughts @calleerlandsson and @teoljungberg?

[homebrew]: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pick.rb#L15

### CODE REVIEW

**Comment by calleerlandsson** [comment]
This seems like a great idea and will probably make the test suite more reliable across different systems!

**Comment by mptre** [comment]
Thanks, merged. @calleerlandsson would you mind crafting a release?

**Comment by teoljungberg** [comment]
I'll update Homebrew with the new release as soon as its cut.

**Comment by teoljungberg** [comment]
Submitted to Homebrew as: https://github.com/Homebrew/homebrew-core/pull/9246

**Pull request merged**
